# Generated by Django 3.1.7 on 2021-05-11 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(choices=[('VH', 'Vehicles'), ('FS', 'Fashion'), ('HO', 'Home'), ('TY', 'Toys'), ('BO', 'Books'), ('EC', 'Electronics'), ('SP', 'Sports')], on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('VH', 'Vehicles'), ('FS', 'Fashion'), ('HO', 'Home'), ('TY', 'Toys'), ('BO', 'Books'), ('EC', 'Electronics'), ('SP', 'Sports')], max_length=64),
        ),
    ]
