# Generated by Django 3.1.7 on 2021-05-11 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210511_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(choices=[('FS', 'Fashion'), ('TY', 'Toys'), ('EC', 'Electronics'), ('HO', 'Home'), ('SP', 'Sports'), ('BO', 'Books'), ('VH', 'Vehicles')], on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('FS', 'Fashion'), ('TY', 'Toys'), ('EC', 'Electronics'), ('HO', 'Home'), ('SP', 'Sports'), ('BO', 'Books'), ('VH', 'Vehicles')], max_length=64),
        ),
    ]
