# Generated by Django 3.1.7 on 2021-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210511_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('FS', 'Fashion'), ('TY', 'Toys'), ('EC', 'Electronics'), ('HO', 'Home'), ('SP', 'Sports'), ('BO', 'Books'), ('VH', 'Vehicles')], max_length=64),
        ),
    ]
