# Generated by Django 3.1.7 on 2021-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210512_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
