# Generated by Django 3.1.7 on 2021-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210513_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='photo',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='url_image',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
