# Generated by Django 3.1.7 on 2021-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210513_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='url_image',
            field=models.URLField(null=True),
        ),
    ]
