# Generated by Django 3.1.7 on 2021-05-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210513_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='url_image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
