# Generated by Django 3.1.7 on 2021-05-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210513_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
