# Generated by Django 3.1.7 on 2021-05-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210518_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='currentbid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.CharField(max_length=300),
        ),
    ]
